#pragma config(Sensor, in3,    pot,            sensorPotentiometer)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#define KP -0.01
#define KI 0.009

task straightPID() {
	int target = -400;
	int IntegralRaw = 0;
	int error = 0;
	int IntegralCap = 1200;
	float a;

	while(true) {
		if(vexRT[Btn7U]==1)
			stopTask(straightPID);
		error = target - SensorValue[pot];
		IntegralRaw += error;
		if(IntegralRaw > IntegralCap) {
			IntegralRaw = IntegralCap;
		}
		if(IntegralRaw < -1*IntegralCap) {
			IntegralRaw = -IntegralCap;
		}
		a = ((KP * error) - (KI * IntegralRaw));
		motor[port4] = -a;
		delay(25);
		if(SensorValue[pot] <= 30) {
			if(SensorValue[pot] >= 0) {
				motor[port4] = 0;
				return;
			}
		}
	}
}

task backwardPid() {
	int target = 3530;
	int IntegralRaw = 0;
	int error = 0;
	int IntegralCap = 1200;
	float a;

	while(true) {
		if(vexRT[Btn7U]==1) {
			stopTask(backwardPid);
		}
		error = target - SensorValue[pot];
		IntegralRaw += error;
		if(IntegralRaw > IntegralCap) {
			IntegralRaw = IntegralCap;
		}
		if(IntegralRaw < -1*IntegralCap) {
			IntegralRaw = -IntegralCap;
		}
		a = ((KP * error) - (KI * IntegralRaw));
		motor[port4] = -a;
		delay(25);
		if(SensorValue[pot] <= 3580) {
			if(SensorValue[pot] >= 3300) {
				motor[port4] = 0;
				return;
			}
		}
	}
}
int lift_target = 414;
task LiftPID()
{
	int error = 999;
	float integralraw = 0;
	float proportion = 0;
	float kp = 0.65;
	float integral = 0;
	float ki = 0.02;
	while(true) {
		error = lift_target - SensorValue[dgtl4];
		proportion = kp * error;
		ki = error / lift_target;
		integralraw += error;
		integral = integralraw * ki;
		motor[port6] = (int)(proportion + integral);
		delay(50);
	}
}
bool pressed = false;

task main()
{
	int doneValue = 1;
	bool done = false;
	while(true) {
		/*if(doneValue== -1) {
			motor[port8]=	(doneValue*vexRT[Ch3]);
			motor[port9] = -doneValue*vexRT[Ch3];
			motor[port2] = -doneValue*vexRT[Ch2];
			motor[port3] = -doneValue*vexRT[Ch2];
		}
		else {*/
			motor[port8] = -(vexRT[Ch2]);
			motor[port9] = vexRT[Ch2];
			motor[port2] = vexRT[Ch3];
			motor[port3] = vexRT[Ch3];
	//	}

		if(vexRT[Btn5D] == 1)
			doneValue = 0-doneValue;

		if (vexRT[Btn6U]){
			motor[port5] = -127;
		}
		else if (vexRT[Btn6D]){
			motor[port5] = 127;
		}
		else {
			motor[port5] = 0;
		}

		motor[port7] = vexRT[Btn8U]*127 - vexRT[Btn8D]*127;
		motor[port4] = vexRT[Btn7L]*50-vexRT[Btn7R]*50;
				//startTask(backwardPid);
			}

}
