
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*        Description: Competition template for VEX EDR                      */
/*                                                                           */
/*---------------------------------------------------------------------------*/

// This code is for the VEX cortex platform
#pragma platform(VEX2)

// Select Download method as "competition"
#pragma competitionControl(Competition)

//Main competition background code...do not modify!
#include "Vex_Competition_Includes.c"
#define KP -0.01
#define KI 0.009

task straightPID() {
	int target = -400;
	int IntegralRaw = 0;
	int error = 0;
	int IntegralCap = 1200;
	float a;

	while(true) {
		if(vexRT[Btn7U]==1)
			stopTask(straightPID);
		error = target - SensorValue[pot];
		IntegralRaw += error;
		if(IntegralRaw > IntegralCap) {
			IntegralRaw = IntegralCap;
		}
		if(IntegralRaw < -1*IntegralCap) {
			IntegralRaw = -IntegralCap;
		}
		a = ((KP * error) - (KI * IntegralRaw));
		motor[port4] = -a;
		delay(25);
		if(SensorValue[pot] <= 30) {
			if(SensorValue[pot] >= 0) {
				motor[port4] = 0;
				return;
			}
		}
	}
}

task backwardPid() {
	int target = 3530;
	int IntegralRaw = 0;
	int error = 0;
	int IntegralCap = 1200;
	float a;

	while(true) {
		if(vexRT[Btn7U]==1) {
			stopTask(backwardPid);
		}
		error = target - SensorValue[pot];
		IntegralRaw += error;
		if(IntegralRaw > IntegralCap) {
			IntegralRaw = IntegralCap;
		}
		if(IntegralRaw < -1*IntegralCap) {
			IntegralRaw = -IntegralCap;
		}
		a = ((KP * error) - (KI * IntegralRaw));
		motor[port4] = -a;
		delay(25);
		if(SensorValue[pot] <= 3580) {
			if(SensorValue[pot] >= 3300) {
				motor[port4] = 0;
				return;
			}
		}
	}
}
/*---------------------------------------------------------------------------*/
/*                          Pre-Autonomous Functions                         */
/*                                                                           */
/*  You may want to perform some actions before the competition starts.      */
/*  Do them in the following function.  You must return from this function   */
/*  or the autonomous and usercontrol tasks will not be started.  This       */
/*  function is only called once after the cortex has been powered on and    */
/*  not every time that the robot is disabled.                               */
/*---------------------------------------------------------------------------*/

void pre_auton()
{
	// Set bStopTasksBetweenModes to false if you want to keep user created tasks
	// running between Autonomous and Driver controlled modes. You will need to
	// manage all user created tasks if set to false.
	bStopTasksBetweenModes = true;

	// Set bDisplayCompetitionStatusOnLcd to false if you don't want the LCD
	// used by the competition include file, for example, you might want
	// to display your team name on the LCD in this function.
	// bDisplayCompetitionStatusOnLcd = false;

	// All activities that occur before the competition starts
	// Example: clearing encoders, setting servo positions, ...
}

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              Autonomous Task                              */
/*                                                                           */
/*  This task is used to control your robot during the autonomous phase of   */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/

task autonomous()
{
	motor[port7] = -100;
	wait1Msec(4000);
	motor[port7] = 0;
	delay(25);
	motor[port2] = -100;
	motor[port3] = -100;
	motor[port8] = 100;
	motor[port9] = -100;
	wait1Msec(2000);
	motor[port2] = 0;
	motor[port3] = 0;
	motor[port8] = 0;
	motor[port9] = 0;
}

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              User Control Task                            */
/*                                                                           */
/*  This task is used to control your robot during the user control phase of */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/

task usercontrol()
{
	// User control code here, inside the loop

	int doneValue = 1;
	bool done = false;
	while(true) {
		if(doneValue== -1) {
			motor[port8]=-(doneValue*vexRT[Ch2]);
			motor[port9] = doneValue*vexRT[Ch2];
			motor[port2] = -doneValue*vexRT[Ch3];
			motor[port3] = -doneValue*vexRT[Ch3];
		}
		else {
			motor[port8]=-(doneValue*vexRT[Ch3]);
			motor[port9] = doneValue*vexRT[Ch3];
			motor[port2] = -doneValue*vexRT[Ch2];
			motor[port3] = -doneValue*vexRT[Ch2];
		}

		if(vexRT[Btn5D] == 1)
			doneValue = 0-doneValue;
		motor[port6] = (vexRT[Btn6D]-0)*127-(vexRT[Btn6U]-0)*127;
		motor[port7] = vexRT[Btn8U]*127 - vexRT[Btn8D]*127;
		motor[port4] = vexRT[Btn7L]*30-vexRT[Btn7R]*30;
	}

}
