#pragma config(Sensor, dgtl2,  enocder,        sensorQuadEncoder)
#pragma config(Motor,  port2,           LBM,           tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port3,           RFM,           tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port4,           RBM,           tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port9,           LFM,           tmotorVex393HighSpeed_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	int angle = 1000;
	int error = 0;
	int count = 0;
	int integral = 0;
	int preverror;
	float ki = 0.01;
//	float power = -127;
	float kp = 0.09;
	float deriv = 0;
	float kd = 0.04;
	float proportion = 0;
//	int cap = 800;
	
	SensorValue[enocder] = 0;
	while(true)
	{
		error = (angle - SensorValue[enocder]);
		integral += error;
		proportion = (error*kp);
		integral *= ki;
		
		motor[port2] = (proportion + integral);
		preverror = error;
		count++;
		delay(25);
		
		
	}
	
	
	
}
