#pragma config(Sensor, in3,    flipperPot,     sensorPotentiometer)
#pragma config(Sensor, dgtl7,  driveEncoder,   sensorQuadEncoder)
#pragma config(Sensor, dgtl9,  liftEncoder,    sensorQuadEncoder)
#pragma config(Motor,  port2,           rightFront,    tmotorVex393_MC29, openLoop, reversed, driveRight)
#pragma config(Motor,  port3,           rightBack,     tmotorVex393_MC29, openLoop, reversed, driveRight)
#pragma config(Motor,  port6,           liftRight,     tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port7,           liftLeft,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           leftFront,     tmotorVex393_MC29, openLoop, driveLeft)
#pragma config(Motor,  port9,           leftBack,      tmotorVex393_MC29, openLoop, driveLeft)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
int lift_target = 300;
#define KP -0.2
#define KI 0.006
static int straightPID(int target) {
	//int target = 460;
	int IntegralRaw = 0;
	int error = 0;
	int IntegralCap = 1200;
	SensorValue[driveEncoder] = 0;
	float a;

	while(true) {
		error = target - SensorValue[driveEncoder];
		IntegralRaw += error;
		if(IntegralRaw > IntegralCap) {
			IntegralRaw = IntegralCap;
		}
		if(IntegralRaw < -1*IntegralCap) {
			IntegralRaw = -IntegralCap;
		}
		a = ((KP * error) - (KI * IntegralRaw));
		motor[leftFront] = -a/2;
		motor[leftBack] = -a/2;
		motor[rightFront] = -a/2;
		motor[rightBack] = -a/2;
		delay(25);
		if(SensorValue[driveEncoder] <= 465) {
			if(SensorValue[driveEncoder] >= 455) {
				motor[leftFront] = 0;
				motor[leftBack] = 0;
				motor[rightBack] = 0;
				motor[rightBack] = 0;
				return 0;
			}
		}
	}
}
static int PID90(int turnTarget) {
	//int target = 460;
	int IntegralRaw = 0;
	int error = 0;
	int IntegralCap = 1200;
	SensorValue[driveEncoder] = 0;
	float a;

	while(true) {
		error = turnTarget - SensorValue[driveEncoder];
		IntegralRaw += error;
		if(IntegralRaw > IntegralCap) {
			IntegralRaw = IntegralCap;
		}
		if(IntegralRaw < -1*IntegralCap) {
			IntegralRaw = -IntegralCap;
		}
		a = ((KP * error) - (KI * IntegralRaw));
		motor[port8] = -a;
		motor[port2] = a;
		motor[port7] = a;
		delay(25);
		if(SensorValue[driveEncoder] <= 465) {
			if(SensorValue[driveEncoder] >= 455) {
				motor[port8] = 0;
				motor[port2] = 0;
				motor[port7] = 0;
				return 0;
			}
		}
	}
}

//PID for Lift

task downLiftPID()
{
	int target = lift_target*-1;
	int error = 999;
	float integralraw = 0;
	float proportion = 0;
	float kp = 0.65;
	float integral = 0;
	float ki = 0.02;
	SensorValue[liftEncoder] = 0;
	while(true) {
		error = target - SensorValue[liftEncoder];
		proportion = kp * error;
		ki = error / target;
		integralraw += error;
		integral = integralraw * ki;
		motor[liftRight] = (int)(proportion + integral);
		motor[liftLeft] = (int)(proportion + integral);
		delay(50);
	}
}

task LiftPID()
{
	int error = 999;
	float integralraw = 0;
	float proportion = 0;
	float kp = 0.65;
	float integral = 0;
	float ki = 0.02;
	SensorValue[liftEncoder] = 0;
	while(true) {
		error = lift_target - SensorValue[liftEncoder];
		proportion = kp * error;
		ki = error / lift_target;
		integralraw += error;
		integral = integralraw * ki;
		motor[liftRight] = (int)(proportion + integral);
		motor[liftLeft] = (int)(proportion + integral);
		delay(50);
	}
}

//

task main()
{
	//straightPID(460);
	//PID90(460);
	//straightPID(10);
	//startTask(LiftPID);
	//straightPID(-10);
	//PID90(460);
	//straightPID(460);
	//startTask(LiftPID);
	if (vexRT[Btn5D]) { straightPID(460); }




}
