#pragma config(Sensor, in3,    flipperPot,     sensorPotentiometer)
#pragma config(Sensor, dgtl7,  driveEncoder,   sensorQuadEncoder)
#pragma config(Sensor, dgtl9,  liftEncoder,    sensorQuadEncoder)
#pragma config(Motor,  port2,           rightFront,    tmotorVex393_MC29, openLoop, reversed, driveRight)
#pragma config(Motor,  port3,           rightBack,     tmotorVex393_MC29, openLoop, reversed, driveRight)
#pragma config(Motor,  port6,           liftRight,     tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port7,           liftLeft,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           leftFront,     tmotorVex393_MC29, openLoop, driveLeft)
#pragma config(Motor,  port9,           leftBack,      tmotorVex393_MC29, openLoop, driveLeft)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#define KP -0.2
#define KI 0.006
static int straightPID() {
	int target = 460;
	int IntegralRaw = 0;
	int error = 0;
	int IntegralCap = 1200;
	SensorValue[driveEncoder] = 0;
	float a;

	while(true) {
		error = target - SensorValue[driveEncoder];
		IntegralRaw += error;
		if(IntegralRaw > IntegralCap) {
			IntegralRaw = IntegralCap;
		}
		if(IntegralRaw < -1*IntegralCap) {
			IntegralRaw = -IntegralCap;
		}
		a = ((KP * error) - (KI * IntegralRaw));
		motor[leftFront] = -a/2;
		motor[leftBack] = -a/2;
		motor[rightFront] = -a/2;
		motor[rightBack] = -a/2;
		delay(25);
		if(SensorValue[driveEncoder] <= 465) {
			if(SensorValue[driveEncoder] >= 455) {
				motor[leftFront] = 0;
				motor[leftBack] = 0;
		    motor[rightBack] = 0;
		    motor[rightBack] = 0;
				return 0;
			}
		}
	}
}
static int PID90() {
	int target = 460;
	int IntegralRaw = 0;
	int error = 0;
	int IntegralCap = 1200;
	SensorValue[driveEncoder] = 0;
	float a;

	while(true) {
		error = target - SensorValue[driveEncoder];
		IntegralRaw += error;
		if(IntegralRaw > IntegralCap) {
			IntegralRaw = IntegralCap;
		}
		if(IntegralRaw < -1*IntegralCap) {
			IntegralRaw = -IntegralCap;
		}
		a = ((KP * error) - (KI * IntegralRaw));
		motor[port8] = -a;
		motor[port2] = a;
		motor[port7] = a;
		delay(25);
		if(SensorValue[driveEncoder] <= 465) {
			if(SensorValue[driveEncoder] >= 455) {
				motor[port8] = 0;
				motor[port2] = 0;
		    motor[port7] = 0;
				return 0;
			}
		}
	}
}




task main()
{
	straightPID();
	PID90();

}
