#pragma config(Sensor, dgtl4,  encoder,        sensorQuadEncoder)
#pragma config(Motor,  port2,           BRM,           tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port7,           FRM,           tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port8,           LEFT,          tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#define KP -0.2
#define KI 0.006

static int straightPID() {
	int target = 460;
	int IntegralRaw = 0;
	int error = 0;
	int IntegralCap = 1200;
	SensorValue[encoder] = 0;
	float a;

	while(true) {
		error = target - SensorValue[encoder];
		IntegralRaw += error;
		if(IntegralRaw > IntegralCap) {
			IntegralRaw = IntegralCap;
		}
		if(IntegralRaw < -1*IntegralCap) {
			IntegralRaw = -IntegralCap;
		}
		a = ((KP * error) - (KI * IntegralRaw));
		motor[port8] = -a/2;
		motor[port2] = -a/2;
		motor[port7] = -a/2;
		delay(25);
		if(SensorValue[encoder] <= 465) {
			if(SensorValue[encoder] >= 455) {
				motor[port8] = 0;
				motor[port2] = 0;
		    motor[port7] = 0;
				return 0;
			}
		}
	}
}

static int PID90 () {
	int target = 460;
	int IntegralRaw = 0;
	int error = 0;
	int IntegralCap = 1200;
	SensorValue[encoder] = 0;
	float a;

	while(true) {
		error = target - SensorValue[encoder];
		IntegralRaw += error;
		if(IntegralRaw > IntegralCap) {
			IntegralRaw = IntegralCap;
		}
		if(IntegralRaw < -1*IntegralCap) {
			IntegralRaw = -IntegralCap;
		}
		a = ((KP * error) - (KI * IntegralRaw));
		motor[port8] = -a;
		motor[port2] = a;
		motor[port7] = a;
		delay(25);
		if(SensorValue[encoder] <= 465) {
			if(SensorValue[encoder] >= 455) {
				motor[port8] = 0;
				motor[port2] = 0;
		    motor[port7] = 0;
				return 0;
			}
		}
	}
}
task main()
{
	straightPID();
	PID90();
}
